kdc_port: ":5232"
kerberos_token: "EMILERPEL95126"
key_bytes: 32
realms:
  - name: "ENTENHAUSEN.COM"
    max_lifetime: 604800
    user_principals:
      - username: "gundel.gaukeley"
        password: "zehner"
      - username: "kater.karlo"
        password: "trud1"
      - username: "donald.duck"
        password: "Hängematte313"
      - username: "dagobert.duck"
        password: "ichliebegeld187"
    service_principals:
      - spn: "srvdc"
        shared_secret: "12345"
      - spn: "srvrdb"
        shared_secret: "54321"
      - spn: "srvrdsh"
        shared_secret: "187"
