kdc_port: ":5232"
kerberos_token: "MEGAKUUL187SALAT"
realms:
  - name: "SALAT.COM"
    user_principals:
      - username: "Meister Proper"
        password: "Salat4"
      - username: "Kater Karlo"
        password: "Simsalabim12"
      - username: "Donald Truck"
        password: "ichbinreich123"
      - username: "Dagobert Truck"
        password: "ichliebegeld123"
    service_principals:
      - name: "dc"
        key: "12345"
      - name: "fs"
        key: "54321"
      - name: "rdsh"
        key: "32145"
